
// Develop api
export const apiConfig = {
  baseUrl: "https://nivyapi-develop.azurewebsites.net/api",
  vendorsBaseUrl: "https://nivyapi-develop.azurewebsites.net/api/Vendor/",
  contestsBaseUrl: "https://nivyapi-develop.azurewebsites.net/api/Contest/",
  venuesBaseUrl: "https://nivyapi-develop.azurewebsites.net/api/Venue/",
  accountsBaseUrl: "https://nivyapi-develop.azurewebsites.net/api/Account/",
  campaignsBaseUrl: "https://nivyapi-develop.azurewebsites.net/api/Compaign/",
  eventsBaseUrl: "https://nivyapi-develop.azurewebsites.net/api/Event/",
};

const endpoints = {
  vendorLogin: `VendorLogIn`,
  createNewAccount: `CreateNewAccount`,
  createVendorAccount: "CreateVendorAccount",
  verifyVendorEmail: "VerifyVendorEmail",
  resetVendorPassword: "ResetVendorPassword",
  verifyPasswordOnLogout: "VerifyPasswordOnLogout",
  getManagedVendors: "GetManagedVendors",
  markAllowDelivery: "MarkAllowDelivery",
  addNewVendor: "AddNewVendor",
  getVendorDetails: "GetVendorDetails",
  deleteVendor: "DeleteVendor",
  markAcceptOrders: "MarkAcceptOrders",
  getVendorOrdersByFilter: "GetVendorOrdersByFilter",
  getVendorCategories: "GetVendorCategories",
  getCategoryItems: "GetCategoryItems",
  addNewCategory: "AddNewCategory",
  deleteCategory: "DeleteCategory",
  reorderVendorCategory: "ReorderVendorCategory",
  listStockItems: "ListStockItems",
  getOrderDetails: "GetOrderDetails",
  markOrderCancelled: "MarkOrderCancelled",
  markOrderCompleted: "MarkOrderCompleted",
  listAssociateAccounts: "ListAssociateAccounts",
  listStockItemOptions: "ListStockItemOptions",
  updateItemInStock: "UpdateItemInStock",
  addAssociateAccount: "AddAssociateAccount",
  getOrganizationVendors: "GetOrganizationVendors",
  getAssociateAccount: "GetAssociateAccount",
  deleteAssociateAccount: "DeleteAssociateAccount",
  editAssociateAccount: "EditAssociateAccount",
  editCategory: "EditCategory",
  reorderCategoryItems: "ReorderCategoryItems",
  editVendor: "EditVendor",
  addNewItem: "AddNewItem",
  addItemImages: "AddItemImages",
  addNewOption: "AddNewOption",
  getItemDetails: "GetItemDetails",
  deleteItem: "DeleteItem",
  getItemOptions: "GetItemOptions",
  getItemOptionDetail: "GetItemOptionDetail",
  addNewOptionChoice: "AddNewOptionChoice",
  deleteOptionCategory: "DeleteOptionCategory",
  deleteItemOptionChoice: "DeleteItemOptionChoice",
  editItemOptionChoice: "EditItemOptionChoice",
  addNewOptionCategory: "AddNewOptionCategory",
  editItemDetails: "EditItemDetails",
  editOptionCategoryName: "EditOptionCategoryName",
  getOrgSections: "GetOrgSections",
  getOrgCategory: "GetOrgCategory",
  getThirdPartyVendors: "GetThirdPartyVendors",
  addThirdPartyVendor: "AddThirdPartyVendor",
  getStripeOnboardingLink: "GetStripeOnboardingLink",
  getOnboardingInfo: "GetOnboardingInfo",
  getVendorVenues: "GetVendorVenues",
  getContestList: "GetContestList",
  addNewContest: "AddNewContest",
  updateContest: "UpdateContest",
  contestDetail: "ContestDetail",
  getRewardList: "GetRewardList",
  addReward: "AddReward",
  rewardDetail: "RewardDetail",
  updateReward: "UpdateReward",
  reorderReward: "ReorderReward",
  addNewCompaign: "AddNewCompaign",
  getCompaignList: "GetCompaignList",
  deleteCompaign: "DeleteCompaign",
  updateCompaign: "UpdateCompaign",
  startContest: "StartContest",
  endContest: "EndContest",
  getContestHistoryList: "GetContestHistoryList",
  submitFutureContestAnswer: "SubmitFutureContestAnswer",
  getEventListByVenueId: "EventListByVenueId",
  postEvent: "AddEvent",
  updateEvent: "UpdateEvent",
  deleteEvent: "DeleteEvent",
};

const methods = {
  get: `GET`,
  post: `POST`,
  put: `PUT`,
  delete: `DELETE`,
};

const header = {
  simpleHeader: {
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
  },
  jsonHeader: {
    Accept: "application/json",
    "Content-Type": "application/json",
  },
  multiImage: "multipart/form-data",
};

// async function authenticatedHeader() {
//   const beareToken = await getAuthTokenDetails();
//   return {
//     Accept: "application/json",
//     "Content-Type": "application/json",
//     Authorization: beareToken,
//   };
// }

export {
  // baseURL,
  // baseURL2,
  // baseURL3,
  // baseURL4,
  // baseURL5,
  // baseURL6,
  endpoints,
  methods,
  header,
  // authenticatedHeader,
};
